- src/bundle/DependencyInjection/IbexaSystemInfoExtension.php
- src/bundle/SystemInfo/Collector/IbexaSystemInfoCollector.php
- tests/bundle/SystemInfo/Collector/IbexaSystemInfoCollectorTest.php
| **JIRA issue**                          | Part of [IBX-1466](https://issues.ibexa.co/browse/IBX-1466)
| **Requires**                            | ibexa/core#17
| **BC breaks**                          | no
Replaced usage of `EzPlatformCoreBundle::VERSION` with `\Ibexa\Contracts\Core\Ibexa::VERSION` introduced via ibexa/core#17
- ~Provided automated test coverage.~
> IBX-1466: Switched to \Ibexa\Contracts\Core\Ibexa::VERSION

- composer.json
- tests/bundle/SystemInfo/Collector/_fixtures/composer.json
- tests/bundle/SystemInfo/Collector/_fixtures/corrupted_composer.json
| **JIRA issue**                          | [IBX-1466](https://issues.ibexa.co/browse/IBX-1466)
| **Requires**                            | ibexa/core#18 and ibexa/compatibility-layer#1
| **BC breaks**                          | no
For more details see ibexa/oss#23
Usage of ezplatform-core has been already dropped via #5 (74bb51c). I dropped additionally Composer script
```composer
"EzSystems\\EzPlatformEncoreBundle\\Composer\\ScriptHandler::compileAssets"
```
Seems the class its referencing does not exist in the current version of `EzPlatformEncoreBundle` delivered by …
> IBX-1466: [Composer] Dropped ezplatform-core requirement

- src/bundle/DependencyInjection/Configuration.php
- src/bundle/DependencyInjection/IbexaSystemInfoExtension.php
| **JIRA issue**                          | [IBX-1589](https://issues.ibexa.co/browse/IBX-1589)
| **BC breaks**                          | yes, requires ibexa/compatibility-layer#5
- ~Provided automated test coverage.~ // full stack Behat coverage
> IBX-1589: Renamed Extension ezplatform_support_tools to ibexa_system_info

- src/bundle/Resources/views/themes/admin/system_info/composer.html.twig
- src/bundle/Resources/views/themes/admin/system_info/hardware.html.twig
- src/bundle/Resources/views/themes/admin/system_info/info.html.twig
- src/bundle/Resources/views/themes/admin/system_info/invalid.html.twig
- src/bundle/Resources/views/themes/admin/system_info/my_ibexa.html.twig
- src/bundle/Resources/views/themes/admin/system_info/php.html.twig
- src/bundle/Resources/views/themes/admin/system_info/repository.html.twig
- src/bundle/Resources/views/themes/admin/system_info/services.html.twig
- src/bundle/Resources/views/themes/admin/system_info/symfony_kernel.html.twig
| **JIRA issue**                          | [IBX-1689](https://issues.ibexa.co/browse/IBX-1689)
| **Type**                                   | improvement
| **BC breaks**                          | yes
Changed all eZ/ez- frontend classes/variables to ibexa
Related PRs:
- https://github.com/ibexa/admin-ui/pull/111
- https://github.com/ibexa/calendar/pull/15
- https://github.com/ibexa/commerce-admin-ui/pull/23
- https://github.com/ibexa/commerce-base-design/pull/11
- https://github.com/ibexa/commerce-checkout/pull/10
- https://github.com/ibexa/commerce-fieldtypes/pull/11
- https://github.com/ibexa/commerce-page-builder/pull/11
- …
> IBX-1689: Change all ez- classes/IDs and eZ variables in frontend part

- src/bundle/DependencyInjection/Compiler/OutputFormatPass.php
- src/bundle/DependencyInjection/Compiler/SystemInfoCollectorPass.php
- src/bundle/Resources/config/services.yaml
- src/bundle/Resources/config/systeminfo.yaml
- src/bundle/Resources/config/view.yaml
| **JIRA issue**                          | [IBX-1694](https://issues.ibexa.co/browse/IBX-1694)
| **BC breaks**                          | yes, requires ibexa/compatibility-layer#12
In this Pull Request we rename Ibexa's dependency injection container service tags according to the map provided by ibexa/compatibility-layer#12 as a part of the rebranding process. Backward compatibility for old service tags is provided by ibexa/compatibility-layer#12.
> IBX-1694: Rebranded dependency injection container service tags

- src/bundle/DependencyInjection/IbexaSystemInfoExtension.php
| **JIRA issue**                          | [IBX-4452](https://issues.ibexa.co/browse/IBX-4452)
| **Type**                                   | improvement
| **Target Ibexa DXP version** | `v4.4`
| **BC breaks**                          | no
| **Doc needed**                       | no
> IBX-4452: Refactored jms_translation configuration using constant

- src/bundle/SystemInfo/Collector/IbexaSystemInfoCollector.php
| **JIRA issue**                          | IBX-3815
| **Target Ibexa version** | `v4.4`
| **BC breaks**                          | no
| **Doc needed**                       | yes
Fixed detection of ibexa/commerce after clean up.
> IBX-3815: Commerce clean up

- src/bundle/DependencyInjection/IbexaSystemInfoExtension.php
- src/bundle/SystemInfo/Collector/IbexaSystemInfoCollector.php
- src/bundle/SystemInfo/Value/IbexaSystemInfo.php
> JIRA: https://issues.ibexa.co/browse/IBX-5813
> IBX-5813: Fixed version detection logic after renaming ibexa/content to ibexa/headless

- composer.json
Also, performed some additional cleanup within `composer.json`.
> Removed unused imports narrowed down via `composer-unused` tool

- composer.json
| :ticket: Issue | IBX-8135|
https://github.com/ibexa/oss/pull/151
https://github.com/ibexa/rest/pull/88
https://github.com/ibexa/dashboard/pull/124
The Ibexa fork of hautelook/templated-uri-bundle is not needed by OSS anymore. Adding the original here as it is used.
Unsure if we should bump to 4.0.
Tests should pass once https://github.com/ibexa/rest/pull/88 is merged.
Sanities only.
> IBX-8135: Remove hautelook/templated-uri-bundle fork

- src/bundle/Resources/config/services.yaml
- src/bundle/Resources/views/themes/admin/system_info/my_ibexa.html.twig
- src/bundle/SystemInfo/Collector/IbexaSystemInfoCollector.php
- src/bundle/SystemInfo/Value/IbexaSystemInfo.php
| :ticket: Issue | IBX-8531 |
https://github.com/ibexa/rector/pull/5
Resolved deprecations in `ibexa/system-info` package.
- Removed deprecated `\Ibexa\Bundle\SystemInfo\SystemInfo\Collector\IbexaSystemInfoCollector::CONTENT_PACKAGES` const
- Removed deprecated `\Ibexa\Bundle\SystemInfo\SystemInfo\Collector\IbexaSystemInfoCollector::ENTERPRISE_PACKAGES` const
- Removed deprecated `\Ibexa\Bundle\SystemInfo\SystemInfo\Value\IbexaSystemInfo` properties
N/A
Update upgrade guide.
> Resolved deprecations in ibexa/system-info package

- src/lib/Service/SearchEngineServiceInfo.php
| :ticket: Issue | IBX-8394 |
Replaced usages of `\Ibexa\Bundle\Core\ApiLoader\RepositoryConfigurationProvider`
with `\Ibexa\Contracts\Core\Container\ApiLoader\RepositoryConfigurationProviderInterface`, using ibexa/rector#6.
No QA needed. Regression tests should be enough.
This is code refactoring without behavior change. No documentation changes needed.
> IBX-8394: Used new RepositoryConfigurationProviderInterface contract

- tests/integration/Kernel.php
| :ticket: Issue | IBX-8137 |
Dropped obsolete swift mailer references from code base
> IBX-8137: [Tests] Dropped obsolete Swift_Mailer from Kernel

- src/bundle/DependencyInjection/IbexaSystemInfoExtension.php
- src/bundle/EventSubscriber/AddXPoweredByHeader.php
| :ticket: Issue | IBX-8138 |
* https://github.com/ibexa/system-info/pull/58 unblock CI
Applied rules from Symfony 5 Rector set lists.
No QA needed. Regression tests should be enough.
This is code refactoring without behavior change. No documentation changes needed.
> IBX-8138: [Rector] Applied rules from Symfony 5 Rector set lists

- src/bundle/SystemInfo/EzcSystemInfoWrapper.php
- tests/bundle/SystemInfo/Collector/EzcPhpSystemInfoCollectorTest.php
| :ticket: Issue | IBX-9413 |
`get_object_vars` - uninitialized properties are considered inaccessible, and thus will not be included in the array. 
If we use types for variables they are treated as uninitialized, which is why the get_object_vars function cannot retrieve them. I also don't see the point of assigning null to each variable to initialize it. During the last change, unfortunately, phpVersion was set to string instead of an array, which after fixing the problem with retrieving variables caused a new error
> IBX-9413: Corrected incorrect type, changed how to retrieve variables

- src/bundle/SystemInfo/Collector/IbexaSystemInfoCollector.php
- tests/bundle/SystemInfo/Collector/IbexaSystemInfoCollectorTest.php
Removes problematic call to FS bound function. This _should_ **globally** cut ibexa platform request processing times by ~ 7 MS depending on the size of the composer.lock file and the storage medium being queried.
See https://issues.ibexa.co/browse/EZP-32460 for more details
By moving the actual parsing of the composer.lock file to when it is required by calls to `IbexaSystemInfoCollector::collect`  instead of the `__construct` method where it is seemingly invoked most requests
Over a large number of requests, especially many short ones this particular call can result in noticeable performance degradation compounded in N+1 scenarios where this code path can be hit many times over the course of a number of requests or longer term use of the admin UI cc @ibexa/php-dev
> EZP-32460: Move problematic call to SystemInfoCollector::collect to outside of constructor

- .github/workflows/ci.yaml
- composer.json
- rector.php
- src/bundle/Command/SystemInfoDumpCommand.php
| :ticket: Issue | IBX-9584  |
Enabled and executed automatic refactoring rules defined for Symfony 6.x.
* [CLI] Replaced deprecated Command::{$defaultName, $defaultDescription} with the AsCommand attribute
* [CLI] Dropped deprecated command aliases
Additionally added rector job to CI setup to prevent merging up code which is not compatible with Symfony 6+.
Sanities.
N/A
> IBX-9584: Resolved Symfony 6.x deprecations

- composer.json
- src/bundle/Controller/SystemInfoController.php
- src/bundle/EventSubscriber/AddXPoweredByHeader.php
- src/bundle/SystemInfo/Collector/ConfigurationSymfonyKernelSystemInfoCollector.php
- src/bundle/SystemInfo/Collector/EzcHardwareSystemInfoCollector.php
- src/bundle/SystemInfo/Collector/EzcPhpSystemInfoCollector.php
- src/bundle/SystemInfo/Collector/IbexaSystemInfoCollector.php
- src/bundle/SystemInfo/Collector/RepositorySystemInfoCollector.php
- src/bundle/SystemInfo/OutputFormat/JsonOutputFormat.php
- src/bundle/SystemInfo/Registry/IdentifierBased.php
- src/bundle/View/SystemInfoViewBuilder.php
- src/lib/EventListener/ConfigureMainMenuListener.php
- src/lib/EventListener/SystemInfoTabGroupListener.php
- src/lib/Storage/Metrics/RepositoryConnectionAwareMetrics.php
- src/lib/Tab/SystemInfo/SystemInfoTab.php
- src/lib/Tab/SystemInfo/TabFactory.php
- tests/bundle/DependencyInjection/Compiler/SystemInfoTabGroupPassTest.php
- tests/bundle/SystemInfo/Collector/EzcHardwareSystemInfoCollectorTest.php
- tests/bundle/SystemInfo/Collector/EzcPhpSystemInfoCollectorTest.php
- tests/bundle/SystemInfo/Collector/IbexaSystemInfoCollectorTest.php
- tests/bundle/SystemInfo/Collector/JsonComposerLockSystemInfoCollectorTest.php
- tests/bundle/SystemInfo/Collector/RepositorySystemInfoCollectorTest.php
- tests/bundle/SystemInfo/Collector/ServicesSystemInfoCollectorTest.php
- tests/bundle/View/SystemInfoViewBuilderTest.php
- tests/lib/EventListener/SystemInfoTabGroupListenerTest.php
- tests/lib/VersionStability/VersionStabilityCheckerTest.php
> [!CAUTION]
> These changes are volatile and - in some repositories - extensive, so they need to be carefully reviewed before merging.
| :ticket: Issue | IBX-9727 |
Added missing strict type hints using `\Rector\Set\ValueObject\SetList::TYPE_DECLARATION` set.
Additionally FQCNs have been imported for every affected file using PHP CS Fixer, in some cases they might override unrelated lines.
PHPStan bump is required due to requirements of Ibexa Rector and Rector itself.
Regression tests.
> IBX-9727: Added missing type hints

- .github/workflows/ci.yaml
- src/lib/Component/Dashboard/EzInfoTwigComponent.php
Service definition was dropped in 
https://github.com/ibexa/system-info/commit/d05bb33deb2fc4d17646b2ee31587637f9bb8d67
during redesign. It seems safe to drop class instead of renaming it or bring it back in anyway.
> Deprecated unused EzInfoTwigComponent

- composer.json
- phpstan.neon
- src/bundle/SystemInfo/Collector/RepositorySystemInfoCollector.php
- src/lib/Storage/Metrics/ContentTypesCountMetrics.php
- src/lib/Storage/Metrics/DraftsCountMetrics.php
- src/lib/Storage/Metrics/PublishedContentObjectsCountMetrics.php
- src/lib/Storage/Metrics/UsersCountMetrics.php
- src/lib/Storage/Metrics/VersionsCountMetrics.php
- tests/bundle/SystemInfo/Collector/RepositorySystemInfoCollectorTest.php
> [!CAUTION]
> # Merge together with other IBX-8471 Pull Requests
> - [ ] Make sure TMP commit(s) are dropped before merging
| :ticket: Issue | IBX-8471 |
Upgrading Symfony dependencies to version 7 along with necessary 3rd party packages and codebase changes.
Key changes:
Sanity tests and/or regression builds.
> IBX-8471: Upgraded codebase to Symfony 7

- src/lib/Storage/Metrics/ContentTypesCountMetrics.php
- src/lib/Storage/Metrics/DraftsCountMetrics.php
- src/lib/Storage/Metrics/PublishedContentObjectsCountMetrics.php
- src/lib/Storage/Metrics/RepositoryConnectionAwareMetrics.php
- src/lib/Storage/Metrics/UsersCountMetrics.php
- src/lib/Storage/Metrics/VersionsCountMetrics.php
| :ticket: Issue | n/a |
|----------------|-----|
Replaces deprecated Doctrine DBAL Platform::getCountExpression() usage with an explicit COUNT expression in SystemInfo.
No functional changes introduced
> Replaced deprecated DBAL count expression
