ibexa/system-info

- src/bundle/Resources/views/themes/admin/system_info/composer.html.twig
- src/bundle/Resources/views/themes/admin/system_info/hardware.html.twig
- src/bundle/Resources/views/themes/admin/system_info/info.html.twig
https://issues.ibexa.co/browse/IBX-1543
> IBX-1543: Replaced deprecated twig functions

- src/bundle/Resources/views/themes/admin/system_info/composer.html.twig
- src/bundle/Resources/views/themes/admin/system_info/info.html.twig
- src/bundle/Resources/views/themes/admin/system_info/symfony_kernel.html.twig
- src/bundle/Resources/views/themes/admin/ui/tab/system_info.html.twig
- tests/bundle/SystemInfo/Collector/_fixtures/composer.json
> IBX-1334: Rebranded ibexa/system-info to use new namespaces

- src/bundle/Resources/translations/systeminfo.en.xliff
- src/bundle/Resources/views/themes/admin/system_info/composer.html.twig
- src/bundle/Resources/views/themes/admin/system_info/hardware.html.twig
- src/bundle/Resources/views/themes/admin/system_info/info.html.twig
- src/bundle/Resources/views/themes/admin/system_info/my_ibexa.html.twig
- src/bundle/Resources/views/themes/admin/system_info/php.html.twig
- src/bundle/Resources/views/themes/admin/system_info/repository.html.twig
- src/bundle/Resources/views/themes/admin/system_info/services.html.twig
- src/bundle/Resources/views/themes/admin/system_info/symfony_kernel.html.twig
https://issues.ibexa.co/browse/IBX-1551
> IBX-1551: Redesigned system information

- src/bundle/Resources/views/themes/admin/ui/tab/system_info.html.twig
**Jira ticket:** https://issues.ibexa.co/browse/IBX-1929
> IBX-1929: Hide collapse button in system info

- src/bundle/DependencyInjection/Compiler/OutputFormatPass.php
- src/bundle/DependencyInjection/Compiler/SystemInfoCollectorPass.php
- src/bundle/Resources/config/service_aliases.yaml
- src/bundle/Resources/config/services.yaml
- src/bundle/Resources/config/systeminfo.yaml
- src/bundle/Resources/config/view.yaml
- src/bundle/View/SystemInfoViewBuilder.php
- src/lib/Tab/SystemInfo/SystemInfoTab.php
- tests/bundle/View/SystemInfoViewBuilderTest.php
> IBX-1853: Rebranded services names

- src/bundle/Resources/config/routing.yaml
- src/bundle/Resources/views/themes/admin/system_info/php.html.twig
- src/lib/EventListener/ConfigureMainMenuListener.php
- tests/bundle/SystemInfo/Collector/_fixtures/composer.json
> IBX-1998: Rebranded routes in ibexa/system-info repository

- src/bundle/Resources/config/default_settings.yaml
- src/bundle/Resources/config/systeminfo.yaml
> IBX-1210: Rebranded @ezdesign ibexa/system-info repository

- src/bundle/Resources/config/services.yaml
- src/bundle/Resources/config/view.yaml
> IBX-1696: Removed class parameters from ibexa/system-info repository

- src/bundle/Controller/SystemInfoController.php
> IBX-1853: Used rebranded namespaces and services names

- src/bundle/SystemInfo/Value/IbexaSystemInfo.php
- tests/bundle/SystemInfo/Collector/ConfigurationSymfonyKernelSystemInfoCollectorTest.php
- tests/bundle/SystemInfo/Collector/EzcHardwareSystemInfoCollectorTest.php
- tests/bundle/SystemInfo/Collector/EzcPhpSystemInfoCollectorTest.php
- tests/bundle/SystemInfo/Collector/JsonComposerLockSystemInfoCollectorTest.php
- tests/bundle/SystemInfo/Collector/RepositorySystemInfoCollectorTest.php
- tests/bundle/SystemInfo/Registry/IdentifierBasedTest.php
> IBX-1853: Used rebranded namespaces in comments

- tests/bundle/SystemInfo/Collector/ConfigurationSymfonyKernelSystemInfoCollectorTest.php
- tests/bundle/SystemInfo/Collector/EzcHardwareSystemInfoCollectorTest.php
- tests/bundle/SystemInfo/Collector/EzcPhpSystemInfoCollectorTest.php
- tests/bundle/SystemInfo/Collector/JsonComposerLockSystemInfoCollectorTest.php
- tests/bundle/SystemInfo/Registry/IdentifierBasedTest.php
- tests/bundle/View/SystemInfoViewBuilderTest.php
> IBX-1853: Used rebranded namespaces in code

- src/lib/EventListener/ConfigureMainMenuListener.php
| Question      | Answer
| ------------- | ---
| Tickets       |   [IBX-1728](https://issues.ibexa.co/browse/IBX-1728)
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | no
| Tests pass?   | yes
| Doc needed?   | no
| License       | [GPL-2.0](https://github.com/ibexa/admin-ui/blob/main/LICENSE)
Wrong navigation structure
> IBX-1728: Wrong navigation structure

- src/bundle/Resources/views/themes/admin/system_info/info.html.twig
JIRA ref: https://issues.ibexa.co/browse/IBX-2871
> IBX-2871: Fixed spacing on some Admin pages

- src/bundle/Command/SystemInfoDumpCommand.php
I noticed some failing CS and some nitpicks in the affected Command.
> Fixed code style and added more strict typing to `SystemInfoDumpCommand`

- src/bundle/Resources/translations/systeminfo.en.xliff
- src/bundle/Resources/views/themes/admin/system_info/my_ibexa.html.twig
JIRA ref: https://issues.ibexa.co/browse/IBX-5456
> IBX-5456: Redundant asterisk in the footnote at System Information tab

- src/bundle/SystemInfo/Value/RepositoryMetrics.php
| ----------------------------------------- | ------------------
| **JIRA issue**                            | [IBX-7409](https://issues.ibexa.co/browse/IBX-7409)
| **Type**                                  | bug
| **Target Ibexa DXP version**              | `v4.6`
| **BC breaks**                             | no
Changed Content Type to Content type
> IBX-7409: Changed Content Type to content type

- src/bundle/Command/SystemInfoDumpCommand.php
> IBX-8224: Dropped BackwardCompatibleCommand

- src/lib/EventListener/ConfigureMainMenuListener.php
Applied rules:
* RenameClassRector
| :ticket: Issue | IBX-XXXXX |
> Added usage of new MenuItemFactoryInterface

- composer.json
- src/bundle/Resources/config/view.yaml
- src/bundle/View/SystemInfoViewBuilder.php
- src/lib/Service/AggregateServiceProvider.php
- src/lib/Storage/AggregateMetricsProvider.php
- src/lib/Tab/SystemInfo/SystemInfoTab.php
- tests/bundle/View/SystemInfoViewBuilderTest.php
> [!CAUTION]
> This is a part of bigger set of changes, to be merged together when ready
> - [x] :exclamation:  **Remove TMP commits before merge** :exclamation:
| :ticket: Issue | IBX-8470  |
This PR bumps Symfony to v6 with codebase upgrades.
Key changes:
Sanities in the form of regression tests.
No documentation required.
> IBX-8470: Upgraded codebase to Symfony 6

- composer.json
| :ticket: Issue | N/A |
Replaced the `hautelook/templated-uri-bundle` dependency with `ibexa/templated-uri-bundle` and updated its version to `^4.0`
Follow up for https://github.com/ibexa/system-info/pull/66 
N/A
N/A
> [Composer] Replaced hautelook/templated-uri-bundle form with ibexa fork

- composer.json
- src/bundle/Resources/config/systeminfo.yaml
- src/bundle/Resources/views/themes/admin/system_info/info.html.twig
- src/lib/Component/Dashboard/EzInfoTwigComponent.php
- tests/integration/Kernel.php
| :ticket: Issue | IBX-9697 |
https://github.com/ibexa/activity-log/pull/123
https://github.com/ibexa/admin-ui/pull/1520
https://github.com/ibexa/app-switcher/pull/11
https://github.com/ibexa/calendar/pull/72
https://github.com/ibexa/connector-ai/pull/122
https://github.com/ibexa/connector-dam/pull/73
https://github.com/ibexa/content-tree/pull/96
https://github.com/ibexa/dashboard/pull/142
https://github.com/ibexa/discounts/pull/216
https://github.com/ibexa/discounts-codes/pull/14
https://github.com/ibexa/form-builder/pull/166
https://github.com/ibexa/image-editor/pull/105
https://github.com/ibexa/order-management/pull/149
https://github.com/ibexa/page-builder/pull/423
https://github.com/ibexa/payment/pull/170 …
> IBX-9697: Refactored components to align with new twig-components package

- src/bundle/Resources/public/scss/_system-info-helper-text.scss
- src/bundle/Resources/public/scss/system-information.scss
> IBX-9940: Removed Sass deprecations

- src/lib/Storage/Metrics/ContentTypesCountMetrics.php
- src/lib/Storage/Metrics/DraftsCountMetrics.php
- src/lib/Storage/Metrics/PublishedContentObjectsCountMetrics.php
- src/lib/Storage/Metrics/UsersCountMetrics.php
- src/lib/Storage/Metrics/VersionsCountMetrics.php
| :ticket: Issue | IBX-9941  |
Adjusted code base to https://github.com/ibexa/core/pull/541 
N/A
N/A
> IBX-9941: Aligned table names to new core schema

- src/lib/Storage/Metrics/ContentTypesCountMetrics.php
| :ticket: Issue | IBX-9941 |
- https://github.com/ibexa/core/pull/574
> IBX-9941: Renamed content type version column to status
